/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupWizardRouteImport } from './routes/setup-wizard'
import { Route as AppLockRouteImport } from './routes/app-lock'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSoftwareUpdateRouteImport } from './routes/_protected/software-update'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRenewLicenseRouteImport } from './routes/_protected/renew-license'
import { Route as ProtectedRecordWeightRouteImport } from './routes/_protected/record-weight'
import { Route as ProtectedLicenseRouteImport } from './routes/_protected/license'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedEditWeightRouteImport } from './routes/_protected/edit-weight'

const SetupWizardRoute = SetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLockRoute = AppLockRouteImport.update({
  id: '/app-lock',
  path: '/app-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSoftwareUpdateRoute = ProtectedSoftwareUpdateRouteImport.update({
  id: '/software-update',
  path: '/software-update',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRenewLicenseRoute = ProtectedRenewLicenseRouteImport.update({
  id: '/renew-license',
  path: '/renew-license',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRecordWeightRoute = ProtectedRecordWeightRouteImport.update({
  id: '/record-weight',
  path: '/record-weight',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLicenseRoute = ProtectedLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEditWeightRoute = ProtectedEditWeightRouteImport.update({
  id: '/edit-weight',
  path: '/edit-weight',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/app-lock': typeof AppLockRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/edit-weight': typeof ProtectedEditWeightRoute
  '/history': typeof ProtectedHistoryRoute
  '/license': typeof ProtectedLicenseRoute
  '/record-weight': typeof ProtectedRecordWeightRoute
  '/renew-license': typeof ProtectedRenewLicenseRoute
  '/settings': typeof ProtectedSettingsRoute
  '/software-update': typeof ProtectedSoftwareUpdateRoute
}
export interface FileRoutesByTo {
  '/app-lock': typeof AppLockRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/edit-weight': typeof ProtectedEditWeightRoute
  '/history': typeof ProtectedHistoryRoute
  '/license': typeof ProtectedLicenseRoute
  '/record-weight': typeof ProtectedRecordWeightRoute
  '/renew-license': typeof ProtectedRenewLicenseRoute
  '/settings': typeof ProtectedSettingsRoute
  '/software-update': typeof ProtectedSoftwareUpdateRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/app-lock': typeof AppLockRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/_protected/edit-weight': typeof ProtectedEditWeightRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/license': typeof ProtectedLicenseRoute
  '/_protected/record-weight': typeof ProtectedRecordWeightRoute
  '/_protected/renew-license': typeof ProtectedRenewLicenseRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/software-update': typeof ProtectedSoftwareUpdateRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-lock'
    | '/setup-wizard'
    | '/edit-weight'
    | '/history'
    | '/license'
    | '/record-weight'
    | '/renew-license'
    | '/settings'
    | '/software-update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app-lock'
    | '/setup-wizard'
    | '/edit-weight'
    | '/history'
    | '/license'
    | '/record-weight'
    | '/renew-license'
    | '/settings'
    | '/software-update'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/app-lock'
    | '/setup-wizard'
    | '/_protected/edit-weight'
    | '/_protected/history'
    | '/_protected/license'
    | '/_protected/record-weight'
    | '/_protected/renew-license'
    | '/_protected/settings'
    | '/_protected/software-update'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AppLockRoute: typeof AppLockRoute
  SetupWizardRoute: typeof SetupWizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-wizard': {
      id: '/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/setup-wizard'
      preLoaderRoute: typeof SetupWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-lock': {
      id: '/app-lock'
      path: '/app-lock'
      fullPath: '/app-lock'
      preLoaderRoute: typeof AppLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/software-update': {
      id: '/_protected/software-update'
      path: '/software-update'
      fullPath: '/software-update'
      preLoaderRoute: typeof ProtectedSoftwareUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/renew-license': {
      id: '/_protected/renew-license'
      path: '/renew-license'
      fullPath: '/renew-license'
      preLoaderRoute: typeof ProtectedRenewLicenseRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/record-weight': {
      id: '/_protected/record-weight'
      path: '/record-weight'
      fullPath: '/record-weight'
      preLoaderRoute: typeof ProtectedRecordWeightRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/license': {
      id: '/_protected/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof ProtectedLicenseRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/edit-weight': {
      id: '/_protected/edit-weight'
      path: '/edit-weight'
      fullPath: '/edit-weight'
      preLoaderRoute: typeof ProtectedEditWeightRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedEditWeightRoute: typeof ProtectedEditWeightRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedLicenseRoute: typeof ProtectedLicenseRoute
  ProtectedRecordWeightRoute: typeof ProtectedRecordWeightRoute
  ProtectedRenewLicenseRoute: typeof ProtectedRenewLicenseRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedSoftwareUpdateRoute: typeof ProtectedSoftwareUpdateRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedEditWeightRoute: ProtectedEditWeightRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedLicenseRoute: ProtectedLicenseRoute,
  ProtectedRecordWeightRoute: ProtectedRecordWeightRoute,
  ProtectedRenewLicenseRoute: ProtectedRenewLicenseRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedSoftwareUpdateRoute: ProtectedSoftwareUpdateRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AppLockRoute: AppLockRoute,
  SetupWizardRoute: SetupWizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
