/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupWizardRouteImport } from './routes/setup-wizard'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRecordWeightRouteImport } from './routes/_protected/record-weight'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedEditWeightRouteImport } from './routes/_protected/edit-weight'

const SetupWizardRoute = SetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRecordWeightRoute = ProtectedRecordWeightRouteImport.update({
  id: '/record-weight',
  path: '/record-weight',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEditWeightRoute = ProtectedEditWeightRouteImport.update({
  id: '/edit-weight',
  path: '/edit-weight',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/edit-weight': typeof ProtectedEditWeightRoute
  '/history': typeof ProtectedHistoryRoute
  '/record-weight': typeof ProtectedRecordWeightRoute
  '/settings': typeof ProtectedSettingsRoute
}
export interface FileRoutesByTo {
  '/setup-wizard': typeof SetupWizardRoute
  '/edit-weight': typeof ProtectedEditWeightRoute
  '/history': typeof ProtectedHistoryRoute
  '/record-weight': typeof ProtectedRecordWeightRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/setup-wizard': typeof SetupWizardRoute
  '/_protected/edit-weight': typeof ProtectedEditWeightRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/record-weight': typeof ProtectedRecordWeightRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup-wizard'
    | '/edit-weight'
    | '/history'
    | '/record-weight'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup-wizard'
    | '/edit-weight'
    | '/history'
    | '/record-weight'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/setup-wizard'
    | '/_protected/edit-weight'
    | '/_protected/history'
    | '/_protected/record-weight'
    | '/_protected/settings'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  SetupWizardRoute: typeof SetupWizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-wizard': {
      id: '/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/setup-wizard'
      preLoaderRoute: typeof SetupWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/record-weight': {
      id: '/_protected/record-weight'
      path: '/record-weight'
      fullPath: '/record-weight'
      preLoaderRoute: typeof ProtectedRecordWeightRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/edit-weight': {
      id: '/_protected/edit-weight'
      path: '/edit-weight'
      fullPath: '/edit-weight'
      preLoaderRoute: typeof ProtectedEditWeightRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedEditWeightRoute: typeof ProtectedEditWeightRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedRecordWeightRoute: typeof ProtectedRecordWeightRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedEditWeightRoute: ProtectedEditWeightRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedRecordWeightRoute: ProtectedRecordWeightRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  SetupWizardRoute: SetupWizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
