PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__settings_new` (
	`id` integer PRIMARY KEY DEFAULT 1 NOT NULL,
	`company_name` text DEFAULT '' NOT NULL,
	`company_address` text DEFAULT '' NOT NULL,
	`company_email` text DEFAULT '' NOT NULL,
	`company_phone` text DEFAULT '' NOT NULL,
	`company_logo_path` text DEFAULT '' NOT NULL,
	`ticket_prefix` text DEFAULT 'SRW' NOT NULL,
	`ticket_footer` text DEFAULT 'Thank you for your custom' NOT NULL,
	`next_ticket_number` integer DEFAULT 1 NOT NULL,
	`serial_port` text DEFAULT 'COM1' NOT NULL,
	`baud_rate` integer DEFAULT 2400 NOT NULL,
	`data_bits` integer DEFAULT 8 NOT NULL,
	`parity` text DEFAULT 'none' NOT NULL,
	`flow_control` text DEFAULT 'none' NOT NULL,
	`stop_bits` integer DEFAULT 1 NOT NULL,
	`auto_open` integer DEFAULT false NOT NULL,
	`indicator_type` text DEFAULT 'd300' NOT NULL,
	`weight_unit` text DEFAULT 'kg' NOT NULL,
	`stable_tolerance` real DEFAULT 0.5 NOT NULL,
	`stable_duration_ms` integer DEFAULT 3000 NOT NULL,
	`theme` text DEFAULT 'system' NOT NULL,
	`print_auto` integer DEFAULT false NOT NULL,
	`print_printer_name` text DEFAULT '' NOT NULL,
	`print_copies` integer DEFAULT 1 NOT NULL,
	`print_paper_size` text DEFAULT '80mm' NOT NULL
);--> statement-breakpoint
INSERT INTO `__settings_new` (
	`id`,
	`company_name`,
	`company_address`,
	`company_email`,
	`company_phone`,
	`company_logo_path`,
	`ticket_prefix`,
	`ticket_footer`,
	`next_ticket_number`,
	`serial_port`,
	`baud_rate`,
	`data_bits`,
	`parity`,
	`flow_control`,
	`stop_bits`,
	`auto_open`,
	`indicator_type`,
	`weight_unit`,
	`stable_tolerance`,
	`stable_duration_ms`,
	`theme`,
	`print_auto`,
	`print_printer_name`,
	`print_copies`,
	`print_paper_size`
)
SELECT
	`id`,
	`company_name`,
	`company_address`,
	`company_email`,
	`company_phone`,
	`company_logo_path`,
	`ticket_prefix`,
	`ticket_footer`,
	`next_ticket_number`,
	`serial_port`,
	`baud_rate`,
	`data_bits`,
	`parity`,
	`flow_control`,
	`stop_bits`,
	`auto_open`,
	`indicator_type`,
	`weight_unit`,
	`stable_tolerance`,
	`stable_duration_ms`,
	`theme`,
	COALESCE(`auto_print`, 0),
	COALESCE(`printer_name`, ''),
	COALESCE(`print_copies`, 1),
	'80mm'
FROM `settings`;--> statement-breakpoint
DROP TABLE `settings`;--> statement-breakpoint
ALTER TABLE `__settings_new` RENAME TO `settings`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
